name: CI

on:
  push:
    branches:
      - main  # Change if your default branch is different
  pull_request:
    branches:
      - main  # Change if your default branch is different

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate PowerShell script
        shell: pwsh
        run: |
          # Check for syntax errors in the PowerShell script
          $scriptPath = "./scripts/CreateStorageAccount.ps1"
          if (Test-Path $scriptPath) {
              try {
                  # Execute the script to validate syntax
                  & $scriptPath
                  Write-Host "Script executed successfully."
              } catch {
                  Write-Host "Script validation failed with the following error: $_"
                  exit 1
              }
          } else {
              Write-Host "Script not found at path: $scriptPath"
              exit 1
          }

      - name: Run Tests
        shell: pwsh
        run: |
          # Here you can add any test commands or validations
          Write-Host "Add your testing logic here."
